# 재구매가 일어난 상품과 회원 리스트 구하기

SELECT USER_ID, PRODUCT_ID 
FROM (SELECT USER_ID, PRODUCT_ID, COUNT(*) AS COUNT
FROM ONLINE_SALE
GROUP BY USER_ID, PRODUCT_ID) AS A
WHERE COUNT >= 2
ORDER BY USER_ID, PRODUCT_ID DESC;
