# 우유와 요거트가 담긴 장바구니
SELECT M.CART_ID
FROM (SELECT DISTINCT CART_ID FROM CART_PRODUCTS WHERE NAME = 'Milk') AS M
JOIN (SELECT DISTINCT CART_ID FROM CART_PRODUCTS WHERE NAME = 'Yogurt') AS Y
ON M.CART_ID = Y.CART_ID
ORDER BY CART_ID;