# 조건에 맞는 사원 정보 조회하기
SELECT SUM(SCORE) AS SCORE, E.EMP_NO, EMP_NAME, POSITION, EMAIL
FROM HR_DEPARTMENT AS D
JOIN HR_EMPLOYEES AS E
ON D.DEPT_ID = E.DEPT_ID
JOIN HR_GRADE AS G
ON E.EMP_NO = G.EMP_NO
WHERE YEAR = 2022
GROUP BY EMP_NO
ORDER BY SCORE DESC
LIMIT 1;