# 물고기 종류 별 대어 찾기
SELECT ID, FISH_NAME, LENGTH
FROM FISH_INFO AS I
JOIN FISH_NAME_INFO AS N
ON I.FISH_TYPE = N.FISH_TYPE
WHERE I.FISH_TYPE IN (SELECT FISH_TYPE AS MAX_LENGTH FROM FISH_INFO GROUP BY FISH_TYPE HAVING LENGTH = MAX(LENGTH))
ORDER BY ID;